security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false    #是否将自己作为客户端注册到Eureka Server[当前模块只是作为Eureka Server服务端所以设为false]
    fetch-registry: false          #是否从Eureka Server获取注册信息[当前是单点的Eureka Server所以不需要同步其它节点的数据]
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
logging:
  level:
    root: INFO