# tomcat
server:
  port: 8002
spring:
  application:
    name: mango-backup
  boot:
    admin:
      client:
        url: "http://localhost:8000"

# backuo datasource
mango:
  backup:
    datasource:
      host: localhost
      userName: root
      password: root
      database: mango
#对应上面系统监控服务
management:
  endpoints:
    web:
      exposure:
        include: "*"